version: "3.7"

services:
  chrome:
    image: selenium/standalone-chrome:3.141.59-20200525
    volumes:
      # to use the host's shared memory.
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
    restart: unless-stopped
